# fly.toml app configuration file generated for hello-vue3 on 2025-03-19T19:26:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-vue3'
primary_region = 'lax'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'
[[services]]
  internal_port = 8000  # 修改内部端口
  protocol = "tcp"

  [services.concurrency]  # 设置并发限制
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]  # 配置 HTTP 端口
    handlers = ["http"]
    port = 80

  [[services.ports]]  # 配置 HTTPS 端口
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  size = 'shared-cpu-1x'
